# Generated by Django 5.1.4 on 2024-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('representante_legal', models.CharField(max_length=100, verbose_name='Representante Legal')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
