# Generated by Django 5.1.4 on 2024-12-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_proveedor_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100, unique=True)),
                ('linea', models.CharField(max_length=100, unique=True)),
                ('unidad', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
