# Generated by Django 5.1.4 on 2024-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parametrosproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosproducto',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parametrosproducto',
            name='linea',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parametrosproducto',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
