# Generated by Django 5.1.4 on 2024-12-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_parametrosproducto_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='linea',
        ),
    ]
