# Generated by Django 5.1.4 on 2024-12-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_producto_cantidad_remove_producto_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='parametros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parametrosproducto'),
        ),
    ]
