# Generated by Django 5.1.4 on 2024-12-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_nombre_producto_nombre_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='codigo_proveedor',
            new_name='id_proveedor',
        ),
    ]
