# Generated by Django 5.1.4 on 2024-12-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_codigo_proveedor_proveedor_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
