# Generated by Django 5.1.4 on 2024-12-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_proveedor_id_alter_proveedor_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
