# Generated by Django 5.1.4 on 2024-12-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notaentrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaEntrada',
        ),
    ]
