# Generated by Django 5.1.4 on 2025-01-12 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_notaentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id_entrada', models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
        ),
    ]
