# Generated by Django 5.1.4 on 2025-03-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_entradamercancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrada', models.CharField(blank=True, max_length=10, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.entradaproducto')),
            ],
        ),
    ]
