# Generated by Django 5.1.4 on 2025-03-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_numerodeentradas_delete_productoentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.entradaproducto')),
            ],
        ),
        migrations.DeleteModel(
            name='NumeroDeEntradas',
        ),
    ]
