# Generated by Django 5.1.4 on 2025-03-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_productoentrada_delete_numerodeentradas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntradaProducto',
            new_name='NumeroEntrada',
        ),
    ]
