# Generated by Django 5.1.4 on 2025-03-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_entradaproducto_numeroentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroentrada',
            name='observacion',
        ),
    ]
